name: Test workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo '{  "timestamp":"4+65416",  "gitrepo":"str841941ing",  "commitid":"string",  "commitauthor":"string",  "tags":"string",  "appro_qa":"string",  "appro_client":"string"}' | curl -k -X POST -H "Content-Type:application/json" -d @- https://f9c9-13-127-106-156.ngrok-free.app/create
       
  
  endFlow:
    runs-on: ubuntu-latest
    steps:
      - name: ok ok bye
        run: echo "bye bye"
        shell: bash
