name: Test workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo '${{ github.event.commits.timestamp }}'
       
  
  endFlow:
    runs-on: ubuntu-latest
    steps:
      - name: ok ok bye
        run: echo "bye bye"
        shell: bash
