name: Test workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: curl -X POST https://f9c9-13-127-106-156.ngrok-free.app/create -H 'Content-Type:" application/json"' -d 'timestamp:${{ github.event.commits[0].timestamp }}
       
       
  
  endFlow:
    runs-on: ubuntu-latest
    steps:
      - name: ok ok bye
        run: echo "bye bye"
        shell: bash
  
